apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: tufin-policy
  labels:
    app: notification-service
    app.kubernetes.io/part-of: tufin-policy
    app.kubernetes.io/component: notification
data:
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: policy-notification-service
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
