apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: tufin-policy
  labels:
    app: notification-service
    app.kubernetes.io/part-of: tufin-policy
    app.kubernetes.io/component: notification
spec:
  selector:
    app: notification-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
