apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: tufin-policy
  labels:
    app: gateway
    app.kubernetes.io/part-of: tufin-policy
    app.kubernetes.io/component: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
