apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tufin-policy
  labels:
    app: postgres
    app.kubernetes.io/part-of: tufin-policy
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: policy_db
  POSTGRES_USER: policy_user
  POSTGRES_PASSWORD: policy_pass
