apiVersion: v1
kind: Service
metadata:
  name: rule-engine
  namespace: tufin-policy
  labels:
    app: rule-engine
    app.kubernetes.io/part-of: tufin-policy
    app.kubernetes.io/component: rule-engine
spec:
  selector:
    app: rule-engine
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
